### ISSUE TITLE
Running private-ghp with localhost

### ISSUE THREAD

**Issue by franyol** [john-dev/private-ghp#1]
I'm testing the code running it in local host for start, setting the OAUTH app's callback URL pointing to http://test.localhost:8080/login/github/callback

Also I'm building using the following config.yaml:

```
port: 8080
publicPort: 8080
domain: localhost
log:
  level: debug
github:
  client:
    id: (UserID)
    secret:  (UserSecret)
pages:
  - subdomain: test #the sub-domain part WITHOUT the main domain
    index: index.html
    cache:
      duration: 1800   
    repository:
      owner: kiwicampus
      name: kronos-project-docs
      branch: privpage # eg. gh-pages
```

After building it, entering test.localhost:8080 and clicking the "Authorize" button; I get redirected to the same authorization path over and over.

This is the terminal I get by doing so:

```
fran@fran:~/Desktop/GITREP/private-ghp$ ./bin/linux/private-ghp --config=sample.config.yaml
DEBU[2022-04-28 13:05:33] loaded config file: sample.config.yaml       
INFO[2022-04-28 13:05:33] listening on 0.0.0.0:8080                    
DEBU[2022-04-28 14:09:41] token recevied from github, redirecting to http://test.localhost:8080// 
DEBU[2022-04-28 14:09:42] token recevied from github, redirecting to http://test.localhost:8080// 
DEBU[2022-04-28 14:09:43] token recevied from github, redirecting to http://test.localhost:8080// 
DEBU[2022-04-28 14:09:43] token recevied from github, redirecting to http://test.localhost:8080// 
DEBU[2022-04-28 14:09:44] token recevied from github, redirecting to http://test.localhost:8080// 
DEBU[2022-04-28 14:09:46] token recevied from github, redirecting to http://test.localhost:8080// 
DEBU[2022-04-28 14:09:46] token recevied from github, redirecting to http://test.localhost:8080// 
DEBU[2022-04-28 14:09:47] token recevied from github, redirecting to http://test.localhost:8080// 
DEBU[2022-04-28 14:09:48] token recevied from github, redirecting to http://test.localhost:8080// 
```

It seems I'm getting into some kind of loop, can you tell me what I'm doing wrong?
